on:
 push:
   branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'

    - name: Build Docker Image
      run: docker build -t app .

    - name: Set up Python-dev
      run: |
        pip install poetry && \
        poetry install

    - name: Run tests
      run: pytest

    - name: Push Docker Image to registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} |
        docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin && \
        docker push app
